### ISSUE TITLE
Blank after "]", generates error

### ISSUE THREAD

**Issue by danilort** [Durandal14/vscode-extension-dbml-viewer#3]
DBML Live Preview 0.0.1
VSCODE 1.82.2
Windows 10 Pro 22H2

Hello,
when **after a closing square bracket**, there are one or more blanks, the extension reports an error.
I tried disabling all extensions, but that's not a solution.

![immagine](https://github.com/Durandal14/vscode-extension-dbml-viewer/assets/16148184/68df8374-7138-4e31-9814-7a2704a4cb27)

![immagine](https://github.com/Durandal14/vscode-extension-dbml-viewer/assets/16148184/71e483a4-8ff7-428d-814c-91303eaad169)

### EXAMPLES
`id int [pk, increment]`

> OK

`id int [pk, increment]                 `

> Error generating SVG

`id int [pk, increment]      //               `

> OK

`nome varchar             `
>OK

**Comment by danilort** [comment]
With VSCODE 1.79 (if I remember correctly), it worked fine

**Comment by danilort** [comment]
`id int [pk, increment]       //       `
OK

**Comment by danilort** [comment]
The error is caused by dbml-render.
SEE: https://github.com/softwaretechnik-berlin/dbml-renderer/issues/28

**Comment by dalurness** [comment]
Likely the same issue, but getting that error also when a table has an array of items. 
`ingredients String[] [not null]`

**Comment by danilort** [comment]
This problem has been fixed in the library dbml-renderer.
See: https://github.com/softwaretechnik-berlin/dbml-renderer/issues/28.
Please update.

**Comment by Durandal14** [comment]
Sure, thanks for the info

**Comment by Durandal14** [comment]
Hi, the extension has been released with the last dbml-renderer version, this value should no longer be a concern
  id integer [pk, increment]
