### ISSUE TITLE
Error using decimal(10,2)

### ISSUE THREAD

**Issue by danilort** [Durandal14/vscode-extension-dbml-viewer#4]
If I use the data_type decima(10,2), I get error.

# using decimal(10,2)

```
Table utenti {
    id int [pk, increment]
    nome varchar     
    data_creato timestamp
    numero decimal(10,2)
    nazione_id int
}
```

![immagine](https://github.com/Durandal14/vscode-extension-dbml-viewer/assets/16148184/816568b2-2abc-40cb-8e59-6c2367b5888d)

# using decimal(10)

```
Table utenti {
    id int [pk, increment]
    nome varchar     
    data_creato timestamp
    numero decimal(10)
    nazione_id int
}

```
![immagine](https://github.com/Durandal14/vscode-extension-dbml-viewer/assets/16148184/ef7b6d7c-dcf9-4a6c-89ff-32649a0d1609)

**Comment by danilort** [comment]
This problem has been fixed in the library dbml-renderer.
See: https://github.com/softwaretechnik-berlin/dbml-renderer/issues/29.
Please update.

**Comment by evandycke** [comment]
Hello @Durandal14, this problem has been fixed in the library dbml-renderer. Can you update please ?
See: softwaretechnik-berlin/dbml-renderer#29.

**Comment by Durandal14** [comment]
Yes I will do it this week, sorry for the delay guys

**Comment by Durandal14** [comment]
Hi, the extension has been released with the last dbml-renderer version, this value should no longer be a concern
decimal(n, m)
