### ISSUE TITLE
Enums with schema are not expected

### ISSUE THREAD

**Issue by Kaev** [Durandal14/vscode-extension-dbml-viewer#6]
The extension currently throws an error if you give an enum a schema.
This should be completely valid according to the DBML docs

**Comment by samuil4** [comment]
I can confirm this behavior.

**Comment by Durandal14** [comment]
Enums are now generated and link to field (last version 0.1.0) 

Table posts {
  id integer [primary key]
  title varchar
  body text [note: 'Content of the post']
  user_id integer
  status status
  created_at timestamp
}

Enum status {
  pending
  active
  inactive
}
