### ISSUE TITLE
Getting Error to Render the DB diagram

### ISSUE THREAD

**Issue by hprasad-dc1104** [Durandal14/vscode-extension-dbml-viewer#7]
Below is the error snap, it's throwing while rendering and nothing came up in Preview.

![image](https://github.com/Durandal14/vscode-extension-dbml-viewer/assets/117668740/5b11e8cd-5bea-447b-b0fd-f1cf4b6a1dc5)

**Comment by hprasad-dc1104** [comment]
I think this extension is not considering or parsing the alias name for tables, due to which it's throwing this error.

**Comment by Durandal14** [comment]
Hi, the use of alias should be possible with the last version

Table posts as P {
  id integer [primary key]
  title varchar
  body text [note: 'Content of the post']
  user_id integer
  status varchar
  created_at timestamp
}

Ref: P.user_id > users.id // many-to-one
